// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC3l6AL06v8LFO19U0gdP_ZDAMzcLxRUg',
    appId: '1:405498617365:web:8b454e4b6cb42939c9781c',
    messagingSenderId: '405498617365',
    projectId: 'quizapp-11387',
    authDomain: 'quizapp-11387.firebaseapp.com',
    storageBucket: 'quizapp-11387.firebasestorage.app',
    measurementId: 'G-7STC9P794D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3pAP2XrhyUcoewMkYbuZLmTZGKUmg8fU',
    appId: '1:405498617365:android:132220a561fcd947c9781c',
    messagingSenderId: '405498617365',
    projectId: 'quizapp-11387',
    storageBucket: 'quizapp-11387.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCERmH3vnX4O4sq4xGT_7scFlGciJI_Gbo',
    appId: '1:405498617365:ios:7b6639f66ba66c9cc9781c',
    messagingSenderId: '405498617365',
    projectId: 'quizapp-11387',
    storageBucket: 'quizapp-11387.firebasestorage.app',
    iosBundleId: 'com.app.quizeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCERmH3vnX4O4sq4xGT_7scFlGciJI_Gbo',
    appId: '1:405498617365:ios:7b6639f66ba66c9cc9781c',
    messagingSenderId: '405498617365',
    projectId: 'quizapp-11387',
    storageBucket: 'quizapp-11387.firebasestorage.app',
    iosBundleId: 'com.app.quizeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC3l6AL06v8LFO19U0gdP_ZDAMzcLxRUg',
    appId: '1:405498617365:web:9d0b41353a132a6ac9781c',
    messagingSenderId: '405498617365',
    projectId: 'quizapp-11387',
    authDomain: 'quizapp-11387.firebaseapp.com',
    storageBucket: 'quizapp-11387.firebasestorage.app',
    measurementId: 'G-DQL5J74QSV',
  );
}
